<?php

namespace App\Repository;

use App\Entity\AliasWWW;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AliasWWWRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasWWWRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, AliasWWW::class);
    }

    //obtiene los alias.
    public function getAlias()
    {
        $em = $this->getEntityManager();

        //obtengo el listado
        $alias = $em->getRepository(AliasWWW::class)->findAll();

        return $alias;
    }
}
