<?php

namespace App\Repository;

use App\Entity\Contenidos;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ContenidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenidosRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Contenidos::class);
    }

    //busca un contenido en la tabla, si no lo encuentra lo agrega.
    public function getContenido($mime)
    {
        $em = $this->getEntityManager();

        //obtengo el contenido que coincida con tipo/subtipo
        $contenido = $em->getRepository(Contenidos::class)->findOneBy(array('mime' => $mime));

        if (!$contenido) { //si el registro esta vacio devuelvo los valores default
            $contenido = new Contenidos($mime);
            $em->persist($contenido);
            $em->flush();
        }

        return $contenido;

    }
}
