<?php

namespace App\Repository;

use App\Entity\Freesites;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * FreesitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreesitesRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Freesites::class);
    }

    //obtiene los sitios free.
    public function isFreeSite($host)
    {
        $em = $this->getEntityManager();

        //obtengo el listado
        $free = $em->getRepository(Freesites::class)->findOneBy(array('patron' => $host));

        if (!$free)
            return 0;
        else
            return 1;

    }
}
