<?php

namespace App\Repository;

use App\Entity\Registro;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * RegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Registro::class);
    }

    public function getRegistro($timestamp)
    {
        $em = $this->getEntityManager();

        //obtengo la unica entrada que debe haber en la tabla
        $registro = $em->getRepository(Registro::class)->find(1);

        if (!$registro) { //si el registro esta vacio devuelvo los valores default
            $registro = new Registro();
            $registro->setLineas(0);
            $registro->setTimestamp($timestamp);
            $registro->setSize(0);
            $em->persist($registro);
            $em->flush();
        }

        return $registro;
    }

    public function setRegistro($timestamp, $size, $lineas_num=0)
    {
        $registro = $this->getRegistro($timestamp);
        
        if($lineas_num != 0){
            $registro->setLineas($lineas_num);
        }
        $registro->setSize($size);
        $registro->setTimestamp($timestamp);

        $em = $this->getEntityManager();
        $em->persist($registro);
        $em->flush();

        return $registro;
    }
}
