<?php

namespace App\Repository;

use App\Entity\AccessLog;
use App\Entity\Usuario;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Usuario::class);
    }

    //busca el usuario en el listado, si no lo encuentra lo agrega
    public function getUser($login)
    {
        $em = $this->getEntityManager();

        //obtengo el usuario
        $usuario = $em->getRepository(Usuario::class)->findOneBy(array('login' => $login));

        if (!$usuario) { //si el registro esta vacio lo inserto en la lista.
            $usuario = new Usuario();
            $usuario->setLogin($login);
            $usuario->setConsumo(0);
            $em->persist($usuario);
            $em->flush();
        }

        return $usuario;
    }

    public function getAcumulado( Usuario $usuario, $anno, $mes)
    {
        $repository = $this->getEntityManager()->getRepository(AccessLog::class);
        $query = $repository->createQueryBuilder('log')
        ->addSelect("SUM(log.carga) as carga")
        ->where('log.usuario = :usuario')
        ->andwhere("YEAR(log.fecha) = :anno")
        ->andwhere("MONTH(log.fecha) = :mes")
        ->groupBy("log.usuario")
        ->setParameter('usuario', $usuario->getId())
        ->setParameter('anno',$anno)
        ->setParameter('mes',$mes)
        ->getQuery();
        $acumulado = $query->getSingleResult();

        return $acumulado['carga'];

    }
}
